env: dev
kafka_partition_override_size: 5242880
dp_downstream_kafka_max_message_bytes: 1572864

processing_lern_kafka_overriden_topics:
  - name: telemetry.assess
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.assess.failed
    retention_time: 172800000
    replication_factor: 1
  - name: content.postpublish.request
    retention_time: 172800000
    replication_factor: 1
  - name: issue.certificate.request
    retention_time: 172800000
    replication_factor: 1
  - name: lms.user.account.merge
    retention_time: 172800000
    replication_factor: 1
  - name: coursebatch.job.request
    retention_time: 172800000
    replication_factor: 1
  - name: learning.events.failed
    retention_time: 172800000
    replication_factor: 1
  - name: enrolment.reconciliation.failed
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.raw
    retention_time: 172800000
    replication_factor: 1
  - name: batch.enrolment.sync.request
    retention_time: 172800000
    replication_factor: 1
  - name: generate.certificate.failed
    retention_time: 172800000
    replication_factor: 1
  - name: generate.certificate.request
    retention_time: 172800000
    replication_factor: 1
  - name: issue.certificate.failed
    retention_time: 172800000
    replication_factor: 1
  - name: activity.agg.failed
    retention_time: 172800000
    replication_factor: 1
  - name: lms.notification
    retention_time: 172800000
    replication_factor: 1
  - name: contentstate.invalid
    retention_time: 172800000
    replication_factor: 1
  - name: programuser.info
    retention_time: 172800000
    replication_factor: 1
  - name: prom.monitoring.metrics
    retention_time: 172800000
    replication_factor: 1
  - name: telemetry.audit
    retention_time: 172800000
    replication_factor: 1

processing_lern_kafka_topics:
  - name: telemetry.assess
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.assess.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: content.postpublish.request
    num_of_partitions: 2
    replication_factor: 1
  - name: issue.certificate.request
    num_of_partitions: 2
    replication_factor: 1
  - name: lms.user.account.merge
    num_of_partitions: 2
    replication_factor: 1
  - name: coursebatch.job.request
    num_of_partitions: 2
    replication_factor: 1
  - name: learning.events.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: enrolment.reconciliation.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: telemetry.raw
    num_of_partitions: 2
    replication_factor: 1
  - name: batch.enrolment.sync.request
    num_of_partitions: 2
    replication_factor: 1
  - name: generate.certificate.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: generate.certificate.request
    num_of_partitions: 2
    replication_factor: 1
  - name: issue.certificate.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: activity.agg.failed
    num_of_partitions: 2
    replication_factor: 1
  - name: lms.notification
    num_of_partitions: 2
    replication_factor: 1
  - name: contentstate.invalid
    num_of_partitions: 2
    replication_factor: 1
  - name: programuser.info
    num_of_partitions: 2
    replication_factor: 1
  - name: prom.monitoring.metrics
    num_of_partitions: 1
    replication_factor: 1
  - name: telemetry.audit
    num_of_partitions: 2
    replication_factor: 1
