version: 2

jobs:
  unit-tests:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: medium
    working_directory: ~/lern
    steps:
      - checkout
      - restore_cache:
          keys:
            - lern-jobs-dependency-cache-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml fi
            - lern-jobs-dependency-cache- # fallback in case previous cache key is not found
      - run: 
          name: Installation of imagemagick
          command: |
            sudo apt-get update --allow-releaseinfo-change || sudo apt-get update --allow-releaseinfo-change
            sudo apt-get install -y imagemagick
      - run:
          name: redis
          command: sudo apt install redis-server -y
      - run:
          name: Execute coverage report
          command: |
            mvn clean scoverage:report -DCLOUD_STORE_GROUP_ID=$CLOUD_STORE_GROUP_ID -DCLOUD_STORE_ARTIFACT_ID=$CLOUD_STORE_ARTIFACT_ID -DCLOUD_STORE_VERSION=$CLOUD_STORE_VERSION
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
            paths:
              - ~/.m2
            key: lern-jobs-dependency-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results
      - run:
           name: sonar
           command: |
             mvn verify -DskipTests=true sonar:sonar -Dlog4j.configuration=./logs sonar:sonar -Dsonar.projectKey=Sunbird-Lern_data-pipeline -Dsonar.organization=sunbird-lern -Dsonar.host.url=https://sonarcloud.io -Dsonar.java.binaries=$(find . -path '*/build/classes/java' | xargs | tr ' ' ',') -Dsonar.coverage.exclusions=**/notification-sdk/**,**/notification/domain/** -Dsonar.test.exclusions=**/notification-sdk/** -Dsonar.exclusions=**/**.java -Dsonar.scala.coverage.reportPaths=/home/circleci/lern/target/scoverage.xml -DCLOUD_STORE_GROUP_ID=$CLOUD_STORE_GROUP_ID -DCLOUD_STORE_ARTIFACT_ID=$CLOUD_STORE_ARTIFACT_ID -DCLOUD_STORE_VERSION=$CLOUD_STORE_VERSION

workflows:
  version: 2
  build-and-test:
    jobs:
      - unit-tests