version: 2.0

jobs:
  unit-tests:
    docker:
      - image: circleci/openjdk:stretch
    resource_class: medium
    working_directory: ~/lern
    steps:
      - checkout
      - restore_cache:
          keys:
            - lern-jobs-dependency-cache-{{ checksum "pom.xml" }} # appends cache key with a hash of pom.xml fi
            - lern-jobs-dependency-cache- # fallback in case previous cache key is not foun
      - run: 
          name: Installation of imagemagick
          command: |
            sudo apt-get update || sudo apt-get update
            sudo apt-get install -y imagemagick
      - run:
          name: Execute clean install
          command: |
            mvn clean install
      - run:
          name: Execute jobs-core scala coverage report
          command: |
            cd jobs-core && mvn scoverage:report
            cd ../dp-core && mvn scoverage:report
            cd ../lms-jobs && mvn scoverage:report
            cd ../notification/notification-job && mvn scoverage:report
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
            paths:
              - ~/.m2
            key: lern-jobs-dependency-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results
      - run:
           name: sonar
           command: |
             mvn -X sonar:sonar -Dlog4j.configuration=./logs sonar:sonar -Dsonar.projectKey=Sunbird-Lern_data-pipeline -Dsonar.organization=sunbird-lern -Dsonar.host.url=https://sonarcloud.io -Dsonar.java.binaries=$(find . -path '*/build/classes/java' | xargs | tr ' ' ',') -Dsonar.scala.coverage.reportPaths=/home/circleci/lern/target/scoverage.xml

workflows:
  version: 2
  build-and-test:
    jobs:
      - unit-tests